### PR TITLE
Add product images, change 1 seed value

### LINKED ISSUE #7: Convert eShopOnWeb images / style to Parts Unlimited
Check Parts Unlimited repo from GDBC2019: [https://dev.azure.com/globaldevopsbootcamp/Challenges/_git/PartsUnlimited-Clean?path=/src/PartsUnlimitedWebsite/images](https://dev.azure.com/globaldevopsbootcamp/Challenges/_git/PartsUnlimited-Clean?path=/src/PartsUnlimitedWebsite/images) for images to reuse and styling options

### PR DESCRIPTION
**Pull request by Oppedijk**
#7 added partsunlimited product images, Seed file needs to be updated further

### CODE REVIEW

**Comment by rajbos** [comment]
That'll work @Oppedijk . Are you planning to add the other images in the seed as well?

**Comment by Oppedijk** [comment]
> That'll work @Oppedijk . Are you planning to add the other images in the seed as well?

@rajbos Added all images as well as the product names and descriptions

**Comment by rajbos** [comment]
Looks good @Oppedijk! I do notice the images are quite large on the index page so we now show 3 images on 1 line. Can we make them smaller or make the page use 9 images instead of 10? That would be a bit nicer.

Also, seems like the detail page fails on ProductId's > 5 (ish). For example `/Product/18`:
image

**Comment by Oppedijk** [comment]
@rajbos Changed the pagesize to 6, much cleaner this way

**Comment by rajbos** [comment]
Tested it, now works correctly

**Pull request merged**
