### PR TITLE
updated all packages to latest

### LINKED ISSUE #34: Add dependabot setup to prevent the updates to packages on .NET 6.0
As @wulfland noticed yesterday: the open PR's that fail from dependabots setup seem to come from the fact that dependabot blindly updates all available NuGet packages to the latest version, without checking if they would work with the target framework version (which is 5). 

- [ ] Add dependabot configuration file to prevent updates to mayor versions

### PR DESCRIPTION
**Pull request by ovebastiansen**
ran locally, no issues found. I looked at the upstream and this was the changes they have done there as well

closes #34

### CODE REVIEW

**Review by rajbos — APPROVED** [review]
Indeed, everything still works :-D. Let's ship it!
🚀

**Comment by rajbos** [comment]
Do note the failing deploys from the push 🤔 . We should double check if that still works after merging....

**Comment by ovebastiansen** [comment]
The problem is change in folder and filestructure on some of the libs used, that failes the deployement. Should perhaps try to use clean target when deploying

**Comment by ovebastiansen** [comment]
now the build is green after adding the workaround described here https://github.com/Azure/webapps-deploy/issues/128#issuecomment-840638737

**Comment by rajbos** [comment]
Awesome work @ovebastiansen !!

**Pull request merged**
